### ISSUE TITLE
Missing client binary in release v1.0.2

### ISSUE THREAD

**Issue by jakobilobi** [InvArch/InvArch-Node#140]
Hello,

In the previous `invarch-collator` release, the client binary was attached as an asset but I can't see it for the latest release ([v1.0.2](https://github.com/InvArch/InvArch-Node/releases/tag/v1.0.2-InvArch)). Will you add it?

Cheers!

**Comment by arrudagates** [comment]
v1.0.2-InvArch contains only a runtime change, but a binary will be attached for convenience.
